

const jokes = [
  'Whats brown and sticky?... your mums poo',
  'What do you call a fat dinosour?... your mum.',
  'When should you hide ina a cupboard?... when your mum comes round.',
  'How about you fuck off and leave me alone?',
  'no.',
  'Knock knock...go fuck yourself',
  'I sold my vacuum cleaner... it was only collecting dust',
  'I don`t like the new pound coin... but then i dislike all change',
  'I`m still making love at 71, which is handy for me because I live at number 63',
  'Women want men in uniforms. In fact when you actually get down to it, all women really want are fascists. Hey, you can say what you like about the Nazis but those guys knew how to turn heads',
  'Have you noticed the way that burns victims stick together?',
  'I had a great business plan ... I was going to build bungalows for dwarfs ... there was only one tiny flaw',
  'What kind of murderer has moral fibre? A cereal killer',
  'I realised I was dyslexic when I went to a toga party dressed as a goat.',
  'Cats have nine lives. Which makes them ideal for experimentation.',
  'I enjoy using the comedy technique of self-deprecation - but I`m not very good at it',
  'Two blind fellows walk into a wall.',
  'Velcro. What a rip-off.',
  'Clowns divorce. Custardy battle.',
  'The universe implodes. No matter.',
  'This joke is about perception and perspective. But it depends how you look at it',
  'The first time I met my wife I knew she was a keeper. She was wearing massive gloves.',
  'What`s the difference between a hippo and a Zippo? One is really heavy, the other is a little lighter.',
  "Have you heard of the band 1023MB? They haven't got a gig yet.",
  "Chuck Norris uses ribbed condoms inside out, so he gets the pleasure.",
  "MacGyver can build an airplane out of gum and paper clips. Chuck Norris can kill him and take it.",
  "Chuck Norris doesn't read books. He stares them down until he gets the information he wants.",
  "If you ask Chuck Norris what time it is, he always answers `Two seconds till`. After you ask `Two seconds to what?`, he roundhouse kicks you in the face.",
  "Chuck Norris lost his virginity before his dad did.",
  "Since 1940, the year Chuck Norris was born, roundhouse kick related deaths have increased 13,000 percent.",
  "Chuck Norris sheds his skin twice a year.",
  "Chuck Norris once challenged Lance Armstrong in a `Who has more testicles?` contest. Chuck Norris won by 5.",
  "There are no steroids in baseball. Just players Chuck Norris has breathed on.",
  "When Chuck Norris goes to donate blood, he declines the syringe, and instead requests a hand gun and a bucket.",
  "Pluto is actually an orbiting group of British soldiers from the American Revolution who entered space after the Chuck gave them a roundhouse kick to the face.",
  "Chuck Norris does not teabag the ladies. He potato-sacks them.",
  "According to the Encyclopedia Brittanica, the Native American `Trail of Tears` has been redefined as anywhere that Chuck Norris walks.",
  "In an average living room there are 1,242 objects Chuck Norris could use to kill you, including the room itself.",
  "The Chuck Norris military unit was not used in the game Civilization 4, because a single Chuck Norris could defeat the entire combined nations of the world in one turn.",
  "Chuck Norris doesn't shower, he only takes blood baths.",
  "Time waits for no man. Unless that man is Chuck Norris.",
  "Chuck Norris can hit you so hard that he can actually alter your DNA. Decades from now your descendants will occasionally clutch their heads and yell `What The Hell was That?`.",
  "In the Bible, Jesus turned water into wine. But then Chuck Norris turned that wine into beer.",
  "Chuck Norris is the only human being to display the Heisenberg uncertainty principle - you can never know both exactly where and how quickly he will roundhouse-kick you in the face.",
  "Faster than a speeding bullet... More powerful than a locomotive... Able to leap tall buildings in a single bound... These are some of Chuck Norris's warm-up exercises.",
  "Chuck Norris is not hung like a horse. Horses are hung like Chuck Norris.",
  "Teenage Mutant Ninja Turtles is based on a true story: Chuck Norris once swallowed a turtle whole, and when he crapped it out, the turtle was six feet tall and had learned karate.",
  "Someone once tried to tell Chuck Norris that roundhouse kicks aren't the best way to kick someone. This has been recorded by historians as the worst mistake anyone has ever made.",
  "Chuck Norris has two speeds: Walk and Kill.",
  "Chuck Norris once shot down a German fighter plane with his finger. By yelling `Bang!`",
  "The opening scene of the movie `Saving Private Ryan` is loosely based on games of dodgeball Chuck Norris played in second grade.",
  "Fool me once, shame on you. Fool Chuck Norris once and he will roundhouse kick you in the face.",
  "Chuck Norris originally appeared in the `Street Fighter II` video game, but was removed by Beta Testers because every button caused him to do a roundhouse kick. When asked about this glitch, Norris replied `That's no glitch.`",
  "If you spell Chuck Norris in Scrabble, you win. Forever.",
  "Someone once videotaped Chuck Norris getting pissed off. It was called Walker: Texas Chain Saw Masacre.",
  "Chuck Norris will attain statehood in 2009. His state flower will be the Magnolia.",
  "A handicapped parking sign does not signify that this spot is for handicapped people. It is actually in fact a warning, that the spot belongs to Chuck Norris and that you will be handicapped if you park there.",
  "Chuck Norris doesn't wash his clothes. He disembowels them.",
  "Chuck Norris doesn't churn butter. He roundhouse kicks the cows and the butter comes straight out.",
  "Police label anyone attacking Chuck Norris as a Code 45-11.... A suicide.",
  "Chuck Norris is the only man to ever defeat a brick wall in a game of tennis.",
  "What was going through the minds of all of Chuck Norris' victims before they died? His shoe.",
  "Chuck Norris once ate three 72 oz. steaks in one hour. He spent the first 45 minutes having sex with his waitress.",
  "There is no theory of evolution, just a list of creatures Chuck Norris allows to live.",
  "Chuck Norris can win a game of Connect Four in only three moves.",
  'My friend said to me: "What rhymes with orange" I said: "no it doesn`t"',
  'To the guy who invented zero... thanks for nothing.',
  "I wish I could clean mirrors for a living. It's just something I can see myself doing.",
  'The first time I got a universal remote control I thought to myself, "This changes everything"',
  "Don't trust atoms. They make up everything.",
  "I bought shoes from a drug dealer once. I don't know what he laced them with, but I was tripping all day.",
  "A man tried to sell me a coffin today. I told him that's the last thing I need.",
  "If you’re struggling to think of what to get someone for Christmas. Get them a fridge and watch their face light up when they open it.",
  "This morning I was wondering where the sun was, but then it dawned on me."
]

function Jokes() {
  this.joke = function(){
    const Index = Math.floor((Math.random() * jokes.length) + 0)
    return jokes[Index]
  }
}

module.exports = Jokes;
